### PR TITLE
encoding compatibility improved

### PR DESCRIPTION
**Pull request by m-final**

### CODE REVIEW

**Review by cmry — CHANGES_REQUESTED** [review]
I would change [line 147](https://github.com/clips/topbox/blob/91636c8549923f0a350a6feac7de868100c70750/stmt.py#L147) to:

```python
csv_file = open("{0}{1}_{2}.csv".format(self.dir, self.name, vsp_type), 'a', encoding='utf-8')
```

Saves you a full loop for encoding.

**Comment by m-final** [comment]
Yeah, you're totally right. Not too familiar with this syntax cuz I'm still in Python 2.7

And just a reminder, from my practice, native Python 2.7 do not support this `open` with 'encoding' argument. Some other changes you may need.  Great work!

**Comment by cmry** [comment]
You could overwrite `open` with [`import io.open as open`](https://docs.python.org/2/library/io.html#io.open) , that might work for both 2.x and 3.x.

**Comment by m-final** [comment]
haha, yes, I just got it from google. You are awesome.

**Comment by cmry** [comment]
feel free to update your pull request with this by the way :)

**Comment by m-final** [comment]
Ohch.. @cmry, I've tried the the new open method, while the encoding problem still got me!

Seems the `io.open` usually accept the UNICODE, but native `csv.writerow` only support ASCII, at least in Python 2.x. 

I now changed the codes back to encoding loops, in order to write the `str` into csv file.

Whats your idea?

Ref: [2.7 CSV module wants unicode, but doesn't want unicode](http://stackoverflow.com/questions/18449233/2-7-csv-module-wants-unicode-but-doesnt-want-unicode)

**Comment by cmry** [comment]
Well, an alternative is to implement the `UnicodeWriter` from [here](https://docs.python.org/2/library/csv.html#examples), but it essentially does the same (`self.writer.writerow([s.encode("utf-8") for s in row])`). I would keep your solution and maybe add `if sys.version_info.major < 3:` as a condition beforehand. I'll merge it like that. :)

**Comment by m-final** [comment]
Agreed. 😉

**Pull request merged**
